services:
  cli:
    build: .
    container_name: backgammon-cli
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: python -m cli.cli

  test:
    build: .
    container_name: backgammon-test
    volumes:
      - .:/app
    command: >
      sh -c "pytest --cov=. --cov-report=term-missing --cov-report=html"

  pygame:
    build: .
    container_name: backgammon-pygame
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    stdin_open: true
    tty: true
    command: python -m pygame_ui.pygameui